### ISSUE TITLE
+1 signal in the first channel is hidden

### ISSUE THREAD

**Issue by mxmilkb** [x42/sisco.lv2#18]
As per IRC https://i.imgur.com/Cbvb22E.png

**Comment by x42** [comment]
Should be fixed since 6936c96e7105. Please test.

**Comment by mxmilkb** [comment]
The problem still exists. Testing with both [CV_Gate16](https://github.com/ryukau/LV2Plugins/tree/master/lv2cvport/CV_Gate16) and AMS CV Source.

**Comment by x42** [comment]
Could it be that it was just the initial size (and resizing fixed it) if so this should be fixed now in v0.8.6-3 ce8139f

**Comment by mxmilkb** [comment]
Yes, resolved, thanks :)
